### ISSUE TITLE
DataTypes fix

### ISSUE THREAD

**Issue by Jayx239** [Jayx239/2JR#43]
lines 138-40
Double precision is 64 bit / 8 Bytes and Single precision is 32 bit / 4 Bytes
@rmc343 Not sure exactly what semi-precision is, 16 bit?

**Comment by rmc343** [comment]
wait on this.. we will talk in person about the confusion

**Comment by Jayx239** [comment]
Apparently I already merged the changes

**Comment by Jayx239** [comment]
reviewed with ryan
